on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest'] # 'ubuntu-latest',

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Install pipenv
      run: pip install pipenv pyinstaller
      
    - name: Install Python Dependencies
      run: pipenv install

    - name: Create requirements.txt
      run: pipenv requirements > req.txt

    - name: Install requirements locally
      run: pip install -r req.txt
      
    - name: Create Templative App/Exe
      run: pyinstaller --distpath ./dist -y -n templative --onefile ./templative/__main__.py --hidden-import engineio.async_drivers.aiohttp --hidden-import engineio.async_aiohttp --collect-all templative

    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: dist/*
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    
